# https://pub.dev/packages/golden_screenshot
name: golden_screenshot
description: Utilities to automate screenshot generation using Flutter's golden tests.
version: 8.2.0
repository: https://github.com/adil192/golden_screenshot

topics:
  - ui
  - testing
  - screenshot

environment:
  sdk: ^3.8.0
  flutter: ">=3.28.0-0.1.pre"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: A generated screenshot for Linux
    path: demo/metadata/en-US/images/flathubScreenshots/2_chat_jane.png
  - description: A generated screenshot for an iPhone
    path: demo/metadata/en-US/images/iphoneScreenshots/2_chat_jane.png
  - description: A generated screenshot for an Android phone
    path: demo/metadata/en-US/images/phoneScreenshots/2_chat_jane.png
  - description: A generated screenshot for an iPad
    path: demo/metadata/en-US/images/ipadScreenshots/2_chat_jane.png
  - description: A generated screenshot for an Android tablet
    path: demo/metadata/en-US/images/tenInchScreenshots/2_chat_jane.png
  - description: A generated screenshot for a Macbook
    path: demo/metadata/en-US/images/macbookScreenshots/2_chat_jane.png

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16+1
  path: ^1.9.1
  web: ^1.1.0
  yaru: ">=8.2.0 <10.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/topbars/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/roboto/Roboto-ExtraLight.ttf
          weight: 200
        - asset: assets/roboto/Roboto-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/roboto/Roboto-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/roboto/Roboto-ExtraBold.ttf
          weight: 800
        - asset: assets/roboto/Roboto-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

