# https://pub.dev/packages/golden_screenshot
name: golden_screenshot
description: Utilities to automate screenshot generation using Flutter's golden tests.
version: 9.1.1
repository: https://github.com/adil192/golden_screenshot

topics:
  - ui
  - testing
  - screenshot

environment:
  sdk: ^3.8.0
  flutter: ">=3.28.0-0.1.pre"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

screenshots:
  - description: A generated screenshot for Linux
    path: demo/metadata/en-US/images/flathubScreenshots/2_chat_jane.png
  - description: A generated screenshot for an iPhone
    path: demo/metadata/en-US/images/iphoneScreenshots/2_chat_jane.png
  - description: A generated screenshot for an Android phone
    path: demo/metadata/en-US/images/phoneScreenshots/2_chat_jane.png
  - description: A generated screenshot for an iPad
    path: demo/metadata/en-US/images/ipadScreenshots/2_chat_jane.png
  - description: A generated screenshot for an Android tablet
    path: demo/metadata/en-US/images/tenInchScreenshots/2_chat_jane.png
  - description: A generated screenshot for a Macbook
    path: demo/metadata/en-US/images/macbookScreenshots/2_chat_jane.png

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16+1
  path: ^1.9.1
  web: ^1.1.0
  yaru: ">=8.2.0 <10.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/topbars/
    - assets/Inter/
